[Enemy]
aggro_range = 1800.0
attack_range = 600.0
max_speed = 3.0

[Character]
brain = {type = "guard"}
death_sound = "guard_death"
bite_sound = "guard_bitten"
team = 2

[AnimationState]
sprite = "guard"

[Collider]
width = 64
height = 128

[Movement]
max_speed = 3.0
ground_acceleration = 9.0
air_acceleration = 7.0
ground_deceleration = 20.0
air_deceleration = 0.5
ground_turn_speed = 20.0
air_turn_speed = 15.0

[Facing]

[Velocity]

[Gravity]
scale = 1.0

[Health]
max = 100

[[WeaponSet]]
type = "Gun"
damage = 2
count = 8
spread = 0.5
speed = 15.0
rate = 0.8333
offset = [32.0, -96.0]

# [DebugColor]
# color = [0, 158, 47, 255]
