[Player]
max_speed = 10.0
ground_acceleration = 9.0
air_acceleration = 3.0
ground_deceleration = 20.0
air_deceleration = 0.5
ground_turn_speed = 20.0
air_turn_speed = 15.0
can_move = true

[Jump]
speed = 10.0
gravity_scale = 0.5
coyote_length = 0.1
buffer_length = 0.1

[AnimationState]
sprite = "vampire"

[Collider]
width = 64
height = 128

[Facing]
