[Player]
max_speed = 10.0
ground_acceleration = 9.0
air_acceleration = 3.0
ground_deceleration = 20.0
air_deceleration = 0.5
ground_turn_speed = 20.0
air_turn_speed = 15.0
can_move = true

[Jump]
speed = 10.0
gravity_scale = 0.5
coyote_length = 0.1
buffer_length = 0.1

[AnimationState]
sprite = "vampire"

[Collider]
width = 64
height = 128

[Facing]

[Velocity]

[Gravity]
scale = 1.0

[Health]
max = 100

[[WeaponSet]]
type = "Melee"
damage = 50
range = 100.0
rate = 0.5

# [[WeaponSet]]
# type = "Gun"
# damage = 10
# count = 1
# spread = 0.1
# speed = 30.0
# rate = 0.1

[[WeaponSet]]
type = "Bite"
damage = 1
range = 64.0

# [DebugColor]
# color = [135, 60, 190, 255]
