[Player]
can_move = true

[Character]
brain = {type = "player"}
team = 1

[Movement]
max_speed = 10.0
ground_acceleration = 15.0
air_acceleration = 5.0
ground_deceleration = 30.0
air_deceleration = 0.5
ground_turn_speed = 20.0
air_turn_speed = 15.0

[Jump]
speed = 16.0
gravity_scale = 0.5
coyote_length = 0.1
buffer_length = 0.1

[AnimationState]
sprite = "vampire"

[Collider]
width = 64
height = 128

[Facing]

[Velocity]

[Gravity]
scale = 1.0

[Health]
max = 100

[[WeaponSet]] # Bite
type = "Bite"
damage = 2
range = 64.0

# Ground attacks

[[WeaponSet]] # Normal attack
type = "Melee"
damage = 50
width = 100.0
height = 32.0
offset = [32.0, 64.0]
rate = 0.75
push = 3.0
can_cancel = true
action = "ATTACK_A"

[[WeaponSet]] # Ground kick
type = "Melee"
damage = 10
width = 100.0
height = 32.0
offset = [32.0, 64.0]
rate = 0.58
push = 15.0
can_cancel = true
action = "ATTACK_C"

[[WeaponSet]] # Ground heavy
type = "Melee"
damage = 100
width = 150.0
height = 32.0
offset = [32.0, 64.0]
rate = 2.6
push = 8.0
can_cancel = false
action = "ATTACK_D"

[[WeaponSet]] # Ground block
type = "Shield"
damage = 20
width = 32.0
rate = 0.6
length = 0.6
deflect = true
action = "ATTACK_E"

# Air attacks

[[WeaponSet]] # Normal air attack
type = "Melee"
damage = 50
width = 100.0
height = 32.0
offset = [32.0, 64.0]
rate = 0.75
push = 6.0
can_cancel = true
action = "ATTACK_B"

[[WeaponSet]] # Drop kick
type = "Charge"
min_damage = 5
max_damage = 70
max_speed = 20.0
width = 150.0
height = 64.0
offset = [32.0, 64.0]
push = 16.0
direction = [1.0, 0.0]
action = "ATTACK_F"

[[WeaponSet]] # Air heavy
type = "Charge"
min_damage = 20
max_damage = 200
max_speed = 80.0
width = 96.0
height = 32.0
offset = [-48.0, 0.0]
push = 0.0
direction = [0.0, 1.0]
action = "ATTACK_G"

[[WeaponSet]] # Air block
type = "Shield"
damage = 20
width = 32.0
rate = 0.5
length = 0.5
deflect = true
action = "ATTACK_H"

# [DebugColor]
# color = [135, 60, 190, 255]

[WeaponMap]
map = [
	["NONE", "ON_FLOOR", 1]
	,["UP", "ON_FLOOR", 2]
	,["DOWN", "ON_FLOOR", 3]
	,["SIDE", "ON_FLOOR", 4]

	,["NONE", "IN_AIR", 5]
	,["UP", "IN_AIR", 6]
	,["DOWN", "IN_AIR", 7]
	,["SIDE", "IN_AIR", 8]
]
