[Player]
can_move = true

[Character]
brain = {type = "player"}
team = 1

[Movement]
max_speed = 10.0
ground_acceleration = 9.0
air_acceleration = 7.0
ground_deceleration = 20.0
air_deceleration = 0.5
ground_turn_speed = 20.0
air_turn_speed = 15.0

[Jump]
speed = 10.0
gravity_scale = 0.5
coyote_length = 0.1
buffer_length = 0.1

[AnimationState]
sprite = "vampire"

[Collider]
width = 64
height = 128

[Facing]

[Velocity]

[Gravity]
scale = 1.0

[Health]
max = 100

[[WeaponSet]] # Bite
type = "Bite"
damage = 1
range = 64.0

# Ground attacks

[[WeaponSet]] # Normal attack
type = "Melee"
damage = 40
range = 100.0
rate = 0.5
push = 6.0
can_cancel = true

[[WeaponSet]] # Ground kick
type = "Melee"
damage = 5
range = 100.0
rate = 0.5
push = 12.0
can_cancel = true

[[WeaponSet]] # Ground heavy
type = "Melee"
damage = 80
range = 150.0
rate = 1.0
push = 8.0
can_cancel = false

[[WeaponSet]] # Ground block
type = "Shield"
width = 32.0
rate = 0.5
length = 0.4
deflect = true

# Air attacks

[[WeaponSet]] # Normal air attack
type = "Melee"
damage = 40
range = 100.0
rate = 0.5
push = 6.0
can_cancel = true

[[WeaponSet]] # Drop kick
type = "Charge"
min_damage = 10
max_damage = 80
max_speed = 10.0
range = 100.0
push = 16.0
direction = [1.0, 0.0]

[[WeaponSet]] # Air heavy
type = "Charge"
min_damage = 20
max_damage = 200
max_speed = 30.0
range = 100.0
push = 0.0
direction = [0.0, 1.0]

[[WeaponSet]] # Air block
type = "Shield"
width = 32.0
rate = 0.5
length = 0.4
deflect = true

# [DebugColor]
# color = [135, 60, 190, 255]

[WeaponMap]
map = [
	["NONE", "ON_FLOOR", 1]
	,["UP", "ON_FLOOR", 2]
	,["DOWN", "ON_FLOOR", 3]
	,["SIDE", "ON_FLOOR", 4]

	,["NONE", "IN_AIR", 5]
	,["UP", "IN_AIR", 6]
	,["DOWN", "IN_AIR", 7]
	,["SIDE", "IN_AIR", 8]
]
