rate = 12
width = 256
height = 128
direction_offset = 14

[length]
IDLE = 28
WALK = 8
ATTACK_A = 9 # Slash
ATTACK_B = 9 # Air slash
ATTACK_C = 7 # Kick
ATTACK_D = 32 # Spin attack
ATTACK_E = 8 # Block
ATTACK_F = 1 # Drop kick
ATTACK_G = 1 # Air heavy
ATTACK_H = 1 # Air block
DIE = 13
FALL = 1
WALL_SLIDE = 1
BITE = 1

[offset]
IDLE = 0
WALK = 1
ATTACK_A = 2 # Slash
ATTACK_B = 3 # Air slash
ATTACK_C = 4 # Kick
ATTACK_D = 6 # Spin attack
ATTACK_E = 7 # Block
ATTACK_F = 12 # Drop kick
ATTACK_G = 10 # Air heavy
ATTACK_H = 11 # Air block
DIE = 5
FALL = 8
WALL_SLIDE = 13
BITE = 9
